### PR TITLE
[chore] Update action.yml

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

This PR updates the Meshery Cloud endpoint for Catalog Applications

Relates to https://github.com/layer5io/meshery-cloud/pull/1001

This PR fixes #

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by theBeginner86** [comment]
@Abhishek-kumar09 
Would you please merge this PR?

I'll make a Meshery Cloud release then.

**Review by leecalcote — APPROVED** [review]
Lgtm

**Review by leecalcote — COMMENTED** [review]
@theBeginner86 isn’t this endpoint backwards? According to the endpoint grouping in the Meshery cloud APi endpoints spreadsheet, content comes before catalog.

**Comment by theBeginner86** [comment]
> @theBeginner86 isn’t this endpoint backwards? According to the endpoint grouping in the Meshery cloud APi endpoints spreadsheet, content comes before catalog.

No, the structure of endpoints is `/catalog/content/<type>`.
Hence it is inline with the backend endpoints.


Screenshot 2023-06-25 at 3 23 29 PM

**Pull request merged**
