### PR TITLE
Migrate Snapshots to Cypress native screenshots

### LINKED ISSUE #68: Workflow failure due to `/` used in relative application path
**Describe the bug**

```
[Invalid workflow file: .github/workflows/meshmap.yml#L46](https://github.com/meshery/meshery/actions/runs/7255261582/workflow)
The workflow is not valid. .github/workflows/meshmap.yml (Line: 46, Col: 21): Unexpected symbol: '/tree/master/install/deployment_yamls/k8s'. Located at position 26 within expression: inputs.fileName == '' && /tree/master/install/deployment_yamls/k8s || inputs.fileName
```

Example - https://github.com/meshery/meshery/actions/runs/7255261582/workflow

This needs to be fixed not in the workflow, but in the configuration wizard / action.

### PR DESCRIPTION
**Pull request by aabidsofi19**
**Notes for Reviewers**

This PR fixes 

This pr migrates the snapshot service to use cypress's screenshoting feature .
reason : 
  -  Cytoscape's export to png doesnt captures only the canvas layer , which prevents from including relations and elements that are rendered in separate layers into the snapshots 

// Notes for maintainers : 

- we are now taking separate light mode and dark mode snapshots 
- the snapshots are in the screentshots directory rather than downloads 
- here is the relative path inside that directory : 
```javascript
const snapshotPath = (designId, theme) => {
  const date = new Date();
  return `MeshMap-${designId}-${date.toDateString()}/${date.toLocaleTimeString()}-${theme}`;
};
```

- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Since this is a filename, we will actually lowercase meshmap. Also, I prefer that we don’t use this name understanding that it may change.

**Comment by leecalcote** [comment]
There are two different types of snapshots right now, stored in two different folders…

**Comment by aabidsofi19** [comment]
@leecalcote  in the same folder : 
image

**Comment by leecalcote** [comment]
It would be good to walk through this change on tomorrow's meeting, @aabidsofi19.

@RipulHandoo, you might like to join that meeting.

**Comment by RipulHandoo** [comment]
@leecalcote Sir.  I'd love to join the meeting tomorrow, but as per my understanding and the [community calendar](https://meshery.io/calendar), our next meeting is scheduled for Monday, 8th Jan 2024. Please let me know if there's any change or if you meant a different meeting.

**Review by theBeginner86 — COMMENTED** [review]
Will you please ensure that these e2e tests don't fail. https://github.com/layer5labs/meshmap-snapshot/actions/runs/7397423535/job/20124507958?pr=74

Since you have updated the download location so please consider updating the tests accordingly. if required 👍 
https://github.com/layer5labs/meshmap-snapshot/blob/master/.github/workflows/file-path-build-test.yml
https://github.com/layer5labs/meshmap-snapshot/blob/master/.github/workflows/url-upload-test.yml

**Comment by aabidsofi19** [comment]
Updated the meshery cloud and meshery.io catalogs : 

https://github.com/meshery/meshery.io/pull/1593

**Review by MUzairS15 — APPROVED** [review]

**Pull request merged**
