### PR TITLE
[fix] donot exit the snapshot on app exceptions

### PR DESCRIPTION
**Pull request by aabidsofi19**
**Notes for Reviewers**

This PR fixes #
the pr prevents the whole snapshot from getting crashed on some uncaught internal exception ( like arising from failed api request using the old axios , in some promise ) 

also logs back the whole exception which might help in debugging them

- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
The logs will be available in the workflow of the repo that runs the Snapshot, right?

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
The screenshot above is still fairly terrible.

**Comment by aabidsofi19** [comment]
> The logs will be available in the workflow of the repo that runs the Snapshot, right?

yeah

**Review by MUzairS15 — APPROVED** [review]
Thanks, was going to add similar debug logs.
The cause we discussed I think that's the whole issue, but to be sure let's see what the error is.

**Pull request merged**
