### PR TITLE
[chore] Fixes invalid semantic error

### PR DESCRIPTION
**Pull request by theBeginner86**
**Notes for Reviewers**

Currently, when a new meshmap snapshot workflow is added, then it replaces `ph_filePath` with `<file-path>`.
Now the issue is that `${{ inputs.fileName == '' && $ph_filePath || inputs.fileName }}` resolves to `${{ inputs.fileName == '' && <file-path> || inputs.fileName }}` which is semantically incorrect as `<file-path>` is treated as variable instead of a string.

So, this PR updates the template workflow file to ensure on replacement the line resolves to `${{ inputs.fileName == '' && '<file-path>' || inputs.fileName }}`.

This would also fix: https://github.com/meshery/meshery/actions/runs/7268615022

This PR fixes #

- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Unfortunately, this means that anyone who has installed the MeshMap Snapshot action needs to update their workflow.

**Comment by leecalcote** [comment]
Ideally, this never exposed in the workflow. Ideally, this is controlled through user selection / configuration in Cloud.

**Comment by theBeginner86** [comment]
> Unfortunately, this means that anyone who has installed the MeshMap Snapshot action needs to update their workflow.

+1

**Comment by leecalcote** [comment]
Acceptance of this fix seems appropriate, while we prudently acknowledge and open an issue to document the need for a shift away from the location in which users configure this setting. Entirely too static here and too dependent upon GitHub Action versions.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
