### PR TITLE
Moving workflow file into templates dir

### LINKED ISSUE #26: Put templates in a directory
Templates: https://github.com/layer5labs/meshmap-snapshot/pull/25

### PR DESCRIPTION
**Pull request by suhail34**
**Notes for Reviewers**

This PR fixes #26

- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Abhishek-kumar09 — APPROVED** [review]
Looks Good to Me . Will merge once the dependent change is merged in meshery-cloud and released.

**Comment by leecalcote** [comment]
Good work, @suhail34 👍

**Comment by theBeginner86** [comment]
> Looks Good to Me . Will merge once the dependent change is merged in meshery-cloud and released.

Here you go: https://github.com/layer5io/meshery-cloud/pull/1136/files

**Comment by Abhishek-kumar09** [comment]
Changes merged in Meshery-Cloud, now just after the release, this PR is good to merge.

**Pull request merged**
